export { App, type AppProps } from './App.js'
export { Chat, type ChatProps } from './Chat.js'
export { MessageList, type MessageListProps, type DisplayMessage } from './MessageList.js'
export { Composer, type ComposerProps } from './Composer.js'
export { VsCodeTransport } from './transport.js'

export { ApprovalPrompt, type ApprovalPromptProps, type PendingApproval } from './approval/ApprovalPrompt.js'
export { DiffView, type DiffViewProps } from './approval/DiffView.js'
export { diffLines, collapseContext, type DiffLine } from './approval/diff.js'

export { SettingsPanel } from './settings/SettingsPanel.js'
export { ProvidersTab, type ProvidersTabProps } from './settings/ProvidersTab.js'
export { ProviderForm, type ProviderFormProps, type ProviderFormValues } from './settings/ProviderForm.js'
export { ScopeBadge, type ScopeBadgeProps } from './settings/ScopeBadge.js'
export { SecretField, type SecretFieldProps } from './settings/SecretField.js'
