import { randomUUID } from 'node:crypto'
import fs from 'node:fs/promises'
import path from 'node:path'
import { redact } from '../logging/redact.js'

/** ~2k tokens, per CLAUDE.md §12. Chars rather than tokens: cheap, and only a cap. */
const DEFAULT_MAX_CHARS = 8_000

export interface TruncationStore {
  /** Persists full output and returns a handle the model can pass to `read_tool_result`. */
  save(content: string): Promise<string>
  read(handle: string, offset: number, limit: number): Promise<string | undefined>
  /**
   * Removes spilled results. Deleting a task must delete the output it spilled, or the
   * directory grows without bound and outlives the transcript that referenced it.
   */
  deleteMany(handles: readonly string[]): Promise<void>
}

/** A `handle` is always one of our own UUIDs; anything else never touches the filesystem. */
function isValidHandle(handle: string): boolean {
  return /^[0-9a-f-]{36}$/i.test(handle)
}

/**
 * Caps oversized tool results, storing the full output on disk and returning a handle
 * the model can re-read with an offset. This exists in v1 specifically because
 * retrofitting it later would change every tool's return path — CLAUDE.md §12.
 */
export class DiskTruncationStore implements TruncationStore {
  /**
   * @param knownSecrets Supplies secret values to strip before writing. Spilled output is
   *   the *largest* thing this project persists and the most likely to contain a secret —
   *   it is whole-file reads and raw command output, kept long after the session. Leaving
   *   it unredacted while redacting the transcript would be incoherent, so redaction
   *   happens here, at the boundary where content actually reaches disk (§15).
   */
  constructor(
    private readonly directory: string,
    private readonly knownSecrets: () => readonly string[] = () => [],
  ) {}

  async save(content: string): Promise<string> {
    const handle = randomUUID()
    await fs.mkdir(this.directory, { recursive: true })
    await fs.writeFile(path.join(this.directory, `${handle}.txt`), redact(content, this.knownSecrets()), 'utf8')
    return handle
  }

  async read(handle: string, offset: number, limit: number): Promise<string | undefined> {
    // Handles are generated by us, but they arrive back via model-supplied arguments —
    // reject anything that isn't a plain UUID rather than trusting it as a path segment.
    if (!isValidHandle(handle)) return undefined
    try {
      const raw = await fs.readFile(path.join(this.directory, `${handle}.txt`), 'utf8')
      return raw.split('\n').slice(offset, offset + limit).join('\n')
    } catch {
      return undefined
    }
  }

  async deleteMany(handles: readonly string[]): Promise<void> {
    await Promise.all(
      handles.filter(isValidHandle).map((handle) =>
        // `force` so a handle already gone (deleted twice, or cleaned up manually) is not
        // an error — deletion should be idempotent.
        fs.rm(path.join(this.directory, `${handle}.txt`), { force: true }),
      ),
    )
  }
}

/**
 * Records every handle spilled through the wrapped store, so a task knows which files it
 * owns. A wrapper rather than a parameter threaded through every tool's return path:
 * `truncateToolResult` is called from one place in the loop, but the handle is produced
 * deep inside it and would otherwise have to be plumbed back out through `ToolResult`.
 */
export class RecordingTruncationStore implements TruncationStore {
  private readonly handles = new Set<string>()

  constructor(private readonly inner: TruncationStore) {}

  async save(content: string): Promise<string> {
    const handle = await this.inner.save(content)
    this.handles.add(handle)
    return handle
  }

  read(handle: string, offset: number, limit: number): Promise<string | undefined> {
    return this.inner.read(handle, offset, limit)
  }

  deleteMany(handles: readonly string[]): Promise<void> {
    for (const handle of handles) this.handles.delete(handle)
    return this.inner.deleteMany(handles)
  }

  /** Handles spilled since the last `startTask()`. */
  spilledHandles(): string[] {
    return [...this.handles]
  }

  /** Called when a task is opened or created, so handles are attributed to the right task. */
  startTask(existing: readonly string[] = []): void {
    this.handles.clear()
    for (const handle of existing) this.handles.add(handle)
  }
}

export interface TruncationResult {
  content: string
  truncated: boolean
}

export async function truncateToolResult(
  content: string,
  store: TruncationStore,
  maxChars: number = DEFAULT_MAX_CHARS,
): Promise<TruncationResult> {
  if (content.length <= maxChars) return { content, truncated: false }

  const handle = await store.save(content)
  const totalLines = content.split('\n').length
  const head = content.slice(0, maxChars)
  return {
    content:
      `${head}\n\n[Output truncated: showing ${maxChars} of ${content.length} characters (${totalLines} lines total). ` +
      `Re-read more with read_tool_result using handle "${handle}".]`,
    truncated: true,
  }
}
