import { randomUUID } from 'node:crypto'
import fs from 'node:fs/promises'
import path from 'node:path'

/** ~2k tokens, per CLAUDE.md §12. Chars rather than tokens: cheap, and only a cap. */
const DEFAULT_MAX_CHARS = 8_000

export interface TruncationStore {
  /** Persists full output and returns a handle the model can pass to `read_tool_result`. */
  save(content: string): Promise<string>
  read(handle: string, offset: number, limit: number): Promise<string | undefined>
}

/**
 * Caps oversized tool results, storing the full output on disk and returning a handle
 * the model can re-read with an offset. This exists in v1 specifically because
 * retrofitting it later would change every tool's return path — CLAUDE.md §12.
 */
export class DiskTruncationStore implements TruncationStore {
  constructor(private readonly directory: string) {}

  async save(content: string): Promise<string> {
    const handle = randomUUID()
    await fs.mkdir(this.directory, { recursive: true })
    await fs.writeFile(path.join(this.directory, `${handle}.txt`), content, 'utf8')
    return handle
  }

  async read(handle: string, offset: number, limit: number): Promise<string | undefined> {
    // Handles are generated by us, but they arrive back via model-supplied arguments —
    // reject anything that isn't a plain UUID rather than trusting it as a path segment.
    if (!/^[0-9a-f-]{36}$/i.test(handle)) return undefined
    try {
      const raw = await fs.readFile(path.join(this.directory, `${handle}.txt`), 'utf8')
      return raw.split('\n').slice(offset, offset + limit).join('\n')
    } catch {
      return undefined
    }
  }
}

export interface TruncationResult {
  content: string
  truncated: boolean
}

export async function truncateToolResult(
  content: string,
  store: TruncationStore,
  maxChars: number = DEFAULT_MAX_CHARS,
): Promise<TruncationResult> {
  if (content.length <= maxChars) return { content, truncated: false }

  const handle = await store.save(content)
  const totalLines = content.split('\n').length
  const head = content.slice(0, maxChars)
  return {
    content:
      `${head}\n\n[Output truncated: showing ${maxChars} of ${content.length} characters (${totalLines} lines total). ` +
      `Re-read more with read_tool_result using handle "${handle}".]`,
    truncated: true,
  }
}
